apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-retrogemini
spec:
  template:
    spec:
      containers:
        - name: container
          image: registry.redhat.io/rhel9/postgresql-15:latest
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: retrogemini-super-admin
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retrogemini-super-admin
                  key: POSTGRES_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: retrogemini-super-admin
                  key: POSTGRES_DB
          volumeMounts:
            - name: retrogemini-postgresql-data
              mountPath: /var/lib/pgsql/data
