apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: retrogemini

resources:
  # Secrets are NOT included - create them manually BEFORE applying
  # See k8s/secrets-templates/ for example files
  - pvc.yaml
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: retrogemini
  app.kubernetes.io/managed-by: kustomize
