apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: retrogemini

resources:
  - postgresql-secret.yaml
  - pvc.yaml
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/part-of: retrogemini
  app.kubernetes.io/managed-by: kustomize
