apiVersion: v1
kind: Secret
metadata:
  name: retrogemini-super-admin
  labels:
    app: retrogemini
type: Opaque
stringData:
  POSTGRES_DB: retrogemini
  POSTGRES_HOST: postgresql
  POSTGRES_PASSWORD: change-me
  POSTGRES_USER: retrogemini
  SUPER_ADMIN_PASSWORD: change-me
