apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-retrogemini
  labels:
    app: postgresql-retrogemini
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgresql-retrogemini
  template:
    metadata:
      labels:
        app: postgresql-retrogemini
    spec:
      volumes:
        - name: retrogemini-postgresql-data
          persistentVolumeClaim:
            claimName: retrogemini-postgresql-data
      containers:
        - name: container
          image: registry.redhat.io/rhel9/postgresql-15:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: retrogemini-super-admin
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retrogemini-super-admin
                  key: POSTGRES_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: retrogemini-super-admin
                  key: POSTGRES_DB
          resources:
            limits:
              cpu: 2m
              memory: 600Mi
            requests:
              cpu: 2m
              memory: 300Mi
          volumeMounts:
            - name: retrogemini-postgresql-data
              mountPath: /var/lib/pgsql/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
