apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retrogemini-postgresql-data
  labels:
    app: postgresql-retrogemini
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard  # Uncomment and adjust for your cluster
